#!/usr/bin/env bash

git clone --bare git@github.com:Andrewvlad/dotfiles.git "$HOME/.dotfiles"

# "config" function since we don't have the dotfile aliases yet
function config {
    git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" "$@"
}

# create backup location
mkdir -p "$HOME/.dotfiles-backup"

if config checkout; then
    # clean checkout
    echo "Checked out dotfiles into $HOME"
else
    echo "Moving conflicting files to ~/.dotfiles-backup"

    # backup existing local dotfiles
    config checkout 2>&1 | grep -E "^\s+\S" | awk '{print $1}' | while read -r file; do
        mkdir -p "$HOME/.dotfiles-backup/$(dirname "$file")"
        mv "$HOME/$file" "$HOME/.dotfiles-backup/$file"
    done

    config checkout
fi

config config status.showUntrackedFiles no
