[font]
size = 12.0

[font.normal]
family = "DepartureMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "Full"
opacity = 0.9

# Swap copy/paste with their Ctrl+Shift mirror
[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u0003"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
chars = "\u0016"
